site_name: RoguelikeEnemyMapper

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - content.code.annotate 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

plugins:
  search:
    lang: 'ja'

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
    - Home:
      - index.md
    - 仕様:
      - overview/index.md
      - システムアーキテクチャ: overview/architecture.md
      - 画面構成:
        - ホーム画面: overview/Interface/HomePage.md
        - 出現敵ナビ画面: overview/Interface/MapperPage.md
        - アイテム識別画面: overview/Interface/AppraisalPage.md
        - データベース作成画面: overview/Interface/CreateDatabasePage.md
      - 機能:
        - 出現敵ナビ: overview/Function/Mapper.md
        - アイテム識別: overview/Function/Appraisal.md
        - データベース作成: overview/Function/CreateDatabase.md
      - データ構造: overview/DataStructure.md
    - メモ:
      - mkdocs: memo/mkdocs.md
